GameList = [{
gameName: "Mission 1: The Vault",
company: "Exit Game",
address: "111 N. Atlantic Blvd, #148",
city: "Monterey Park",
state: "CA",
zip: "91754",
datePlayed: new Date("11/3/14"),
fini: false,
won: false,
playedWith: "Just me"
},{
gameName: "Crazy Secret Laboratory",
company: "Real Escape Room",
address: "18558 Gale Ave #250",
city: "City of Industry",
state: "CA",
zip: "91748",
datePlayed: new Date("11/10/14"),
fini: true,
won: true,
playedWith: "Sharron"
},{
gameName: "Sherlock Room",
company: "Live Escape Room",
address: "2959 Westwood Drive",
city: "Las Vegas",
state: "NV",
zip: "89109",
datePlayed: new Date("11/28/14"),
fini: false,
won: false,
playedWith: "Group"
},{
gameName: "Trap Room",
company: "Live Escape Room",
address: "2959 Westwood Drive",
city: "Las Vegas",
state: "NV",
zip: "89109",
datePlayed: new Date("11/29/14"),
fini: true,
won: true,
playedWith: "Sharron"
},{
gameName: "The Study",
company: "Puzzalarium",
address: "841 14th St",
city: "San Diego",
state: "CA",
zip: "92101",
datePlayed: new Date("12/13/14"),
fini: true,
won: true,
playedWith: "Sharron"
},{
gameName: "Hostage Rescue",
company: "Vegas Lockdown",
address: "3271 Highland Drive, #715",
city: "Las Vegas",
state: "NV",
zip: "89109",
datePlayed: new Date("5/4/15"),
fini: true,
won: true,
playedWith: "Bret Hilby, Janet Hilby, Brenda Hilby, Brenda Hilby's friend"
},{
gameName: "Mob Boss",
company: "Vegas Lockdown",
address: "3271 Highland Drive, #715",
city: "Las Vegas",
state: "NV",
zip: "89109",
datePlayed: new Date("5/4/15"),
fini: true,
won: true,
playedWith: "Bret Hilby, Janet Hilby, Brenda Hilby, Brenda Hilby's friend"
},{
gameName: "Wrongfully Accused",
company: "Live Escape Adventure",
address: "6376 W. Sahara Ave",
city: "Las Vegas",
state: "NV",
zip: "89146",
datePlayed: new Date("5/9/15"),
fini: true,
won: true,
playedWith: "Sharron"
},{
gameName: "Payback",
company: "Live Escape Adventure",
address: "6376 W. Sahara Ave",
city: "Las Vegas",
state: "NV",
zip: "89146",
datePlayed: new Date("5/9/15"),
fini: true,
won: true,
playedWith: "Sharron"
},{
gameName: "Pharaoh's Curse",
company: "Live Escape Adventure",
address: "6376 W. Sahara Ave",
city: "Las Vegas",
state: "NV",
zip: "89146",
datePlayed: new Date("5/13/15"),
fini: true,
won: true,
playedWith: "Just me"
},{
gameName: "Crazy Professor",
company: "Vegas Lockdown",
address: "3271 Highland Drive, #715",
city: "Las Vegas",
state: "NV",
zip: "89109",
datePlayed: new Date("5/20/15"),
fini: true,
won: true,
playedWith: "Bret Hilby, Janet Hilby, Brenda Hilby, Brenda Hilby's friend"
},{
gameName: "White Lie",
company: "Live Game Escape",
address: "3300 S Jones Blvd. Suite 201",
city: "Las Vegas",
state: "NV",
zip: "89146",
datePlayed: new Date("6/9/15"),
fini: true,
won: true,
playedWith: "Sharron"
},{
gameName: "Atelophobia",
company: "Countdown Las Vegas",
address: "2959 Westwood Drive",
city: "Las Vegas",
state: "NV",
zip: "89109",
datePlayed: new Date("6/20/15"),
fini: false,
won: false,
playedWith: "Group"
},{
gameName: "Empress of the Globe",
company: "Live Game Escape",
address: "3300 S Jones Blvd. Suite 201",
city: "Las Vegas",
state: "NV",
zip: "89146",
datePlayed: new Date("8/22/15"),
fini: true,
won: true,
playedWith: "Sharron, Bailey, Avery"
},{
gameName: "The Next Civilization",
company: "Escape or Die!",
address: "3064 W. Post Ave",
city: "Las Vegas",
state: "NV",
zip: "89118",
datePlayed: new Date("1/3/16"),
fini: true,
won: true,
playedWith: "Sharron"
},{
gameName: "Zombie Virus",
company: "Escape or Die!",
address: "3064 W. Post Ave",
city: "Las Vegas",
state: "NV",
zip: "89118",
datePlayed: new Date("5/28/16"),
fini: true,
won: true,
playedWith: "Sharron"
},{
gameName: "Spite Sherlock",
company: "Rush to Escape",
address: "2185 E. Windmill Lane",
city: "Las Vegas",
state: "NV",
zip: "89021",
datePlayed: new Date("6/25/16"),
fini: true,
won: true,
playedWith: "Sharron"
},{
gameName: "The Study",
company: "The Sleuthbox",
address: "2400 W Medtronic Way",
city: "Tempe",
state: "AZ",
zip: "85281",
datePlayed: new Date("7/2/16"),
fini: false,
won: false,
playedWith: "Sharron"
},{
gameName: "The Whimsical Library",
company: "Epic Escape Game Phoenix",
address: "844 N. 4TH Avenue",
city: "Phoenix",
state: "AZ",
zip: "85003",
datePlayed: new Date("7/2/16"),
fini: false,
won: false,
playedWith: "Sharron"
},{
gameName: "The Cult of Mithras",
company: "Dare to Escape",
address: "9875 S Priest Drive #101",
city: "Tempe",
state: "AZ",
zip: "85284",
datePlayed: new Date("7/3/16"),
fini: true,
won: true,
playedWith: "Sharron"
},{
gameName: "Escape Game Night",
company: "Escape Adventure",
address: "7125 E. Southern Avenue, Suite 101",
city: "Mesa",
state: "AZ",
zip: "85209",
datePlayed: new Date("7/3/16"),
fini: false,
won: false,
playedWith: "Sharron"
},{
gameName: "Escape Wonderland",
company: "Escape Adventure",
address: "7125 E. Southern Avenue, Suite 101",
city: "Mesa",
state: "AZ",
zip: "85209",
datePlayed: new Date("7/3/16"),
fini: false,
won: false,
playedWith: "Sharron"
},{
gameName: "Mapuche",
company: "Xtreme Escape",
address: "105 E. Reno Ave, Suite 100",
city: "Las Vegas",
state: "NV",
zip: "89119",
datePlayed: new Date("8/19/16"),
fini: true,
won: true,
playedWith: "Seth"
},{
gameName: "Ocean's Dark 11",
company: "Xtreme Escape",
address: "105 E. Reno Ave, Suite 100",
city: "Las Vegas",
state: "NV",
zip: "89119",
datePlayed: new Date("8/26/16"),
fini: true,
won: true,
playedWith: "Sharron, Bret Hilby, Janet Hilby"
},{
gameName: "Da Vinci's Secret",
company: "Mystery Escape Room",
address: "46 W St. George Blvd",
city: "St. George",
state: "UT",
zip: "84770",
datePlayed: new Date("9/3/16"),
fini: false,
won: false,
playedWith: "Sharron, eight strangers"
},{
gameName: "The Great Escape",
company: "Xtreme Escape",
address: "105 E. Reno Ave, Suite 100",
city: "Las Vegas",
state: "NV",
zip: "89119",
datePlayed: new Date("11/5/16"),
fini: true,
won: true,
playedWith: "Sharron, Bret, Janet, Brenda, Stephanie Hilby"
},{
gameName: "Prison Break",
company: "Rush to Escape",
address: "2185 E. Windmill Lane",
city: "Las Vegas",
state: "NV",
zip: "89021",
datePlayed: new Date("11/11/16"),
fini: false,
won: false,
playedWith: "Sharron"
},{
gameName: "Code 13",
company: "Xterious Escape",
address: "105 E. Reno Ave, Suite 100",
city: "Las Vegas",
state: "NV",
zip: "89119",
datePlayed: new Date("1/2/17"),
fini: true,
won: true,
playedWith: "Sharron"
},{
gameName: "Escape from Mars",
company: "ESCAPEability",
address: "3100 S. Durango #106",
city: "Las Vegas",
state: "NV",
zip: "89117",
datePlayed: new Date("1/28/17"),
fini: true,
won: true,
playedWith: "Sharron, Avery"
},{
gameName: "Pompeii",
company: "ESCAPEability",
address: "3100 S. Durango #106",
city: "Las Vegas",
state: "NV",
zip: "89117",
datePlayed: new Date("2/11/17"),
fini: true,
won: true,
playedWith: "Sharron, Bailey, Avery"
},{
gameName: "Budapest Express",
company: "Escapology",
address: "2797 S Maryland Pkwy",
city: "Las Vegas",
state: "NV",
zip: "89109",
datePlayed: new Date("3/23/17"),
fini: false,
won: false,
playedWith: "Sharron"
},{
gameName: "The Antidote",
company: "Escapology",
address: "2797 S Maryland Pkwy",
city: "Las Vegas",
state: "NV",
zip: "89109",
datePlayed: new Date("3/29/17"),
fini: true,
won: true,
playedWith: "Seth"
},{
gameName: "Shanghaied",
company: "Escapology",
address: "2797 S Maryland Pkwy",
city: "Las Vegas",
state: "NV",
zip: "89109",
datePlayed: new Date("4/6/17"),
fini: true,
won: true,
playedWith: "Seth"
},{
gameName: "Pirate Captain",
company: "Escape Games Riverside",
address: "6788 Magnolia Avenue",
city: "Riverside",
state: "CA",
zip: "92506",
datePlayed: new Date("4/22/17"),
fini: false,
won: false,
playedWith: "Sharron"
},{
gameName: "The Study",
company: "Open Door Escape Games",
address: "19 E Citrus #208",
city: "Redlands",
state: "CA",
zip: "92373",
datePlayed: new Date("4/23/17"),
fini: true,
won: true,
playedWith: "Group"
},{
gameName: "Curiosity Shop",
company: "Curiosity Shop",
address: "3466 University Ave",
city: "Riverside",
state: "CA",
zip: "92501",
datePlayed: new Date("4/23/17"),
fini: true,
won: true,
playedWith: "Sharron, Gary, Stephanie, Kim, Lewell"
},{
gameName: "Mysterious Stranger",
company: "Steal and Escape",
address: "2602 Transportation Ave, Suite B",
city: "Chula Vista/National City",
state: "CA",
zip: "91950",
datePlayed: new Date("4/27/17"),
fini: true,
won: false,
playedWith: "Sharron"
},{
gameName: "The Great Pirate Escape",
company: "Brainy Actz",
address: "28481 Rancho California Rd. Suite #108",
city: "Temecula",
state: "CA",
zip: "92590",
datePlayed: new Date("4/28/17"),
fini: true,
won: true,
playedWith: "Sharron"
},{
gameName: "The Lost Jungle Safari",
company: "Brainy Actz",
address: "28481 Rancho California Rd. Suite #108",
city: "Temecula",
state: "CA",
zip: "92590",
datePlayed: new Date("4/28/17"),
fini: true,
won: true,
playedWith: "Group"
},{
gameName: "Cursed Cabin",
company: "Lockdown Sahara",
address: "6376 W. Sahara Ave",
city: "Las Vegas",
state: "NV",
zip: "89146",
datePlayed: new Date("7/9/17"),
fini: true,
won: true,
playedWith: "Bret, Janet"
},{
gameName: "Cuban Crisis",
company: "Escapology",
address: "2797 S Maryland Pkwy",
city: "Las Vegas",
state: "NV",
zip: "89109",
datePlayed: new Date("9/24/17"),
fini: true,
won: true,
playedWith: "Sharron, Bailey, Avery"
},{
gameName: "Arizona Shootout",
company: "Escapology",
address: "2797 S Maryland Pkwy",
city: "Las Vegas",
state: "NV",
zip: "89109",
datePlayed: new Date("10/13/17"),
fini: true,
won: true,
playedWith: "Sharron, Bailey, Avery, Matt"
},{
gameName: "Draco's Castle",
company: "5 Wits",
address: "4270 Palisade Center Drive",
city: "West Nyack",
state: "NY",
zip: "10994",
datePlayed: new Date("11/2/17"),
fini: true,
won: true,
playedWith: "Nick"
},{
gameName: "The Tomb",
company: "5 Wits",
address: "4270 Palisade Center Drive",
city: "West Nyack",
state: "NY",
zip: "10994",
datePlayed: new Date("11/2/17"),
fini: true,
won: true,
playedWith: "Nick"
},{
gameName: "Deep Space",
company: "5 Wits",
address: "4270 Palisade Center Drive",
city: "West Nyack",
state: "NY",
zip: "10994",
datePlayed: new Date("11/2/17"),
fini: true,
won: true,
playedWith: "Nick"
},{
gameName: "Escape the Nemesis",
company: "Mission Escape Games",
address: "55 Chrystie St",
city: "New York",
state: "NY",
zip: "10002",
datePlayed: new Date("11/4/17"),
fini: true,
won: true,
playedWith: "Omer, James Carson, Jason Richard, Marketa"
},{
gameName: "Maze of Hakaina",
company: "Komnata Quest Escape Room NYC",
address: "160 Pearl St #202",
city: "New York",
state: "NY",
zip: "10005",
datePlayed: new Date("11/4/17"),
fini: true,
won: true,
playedWith: "Omer, James Carson, Jason Richard, Marketa"
},{
gameName: "The Escape Test",
company: "Paradiso Escape",
address: "38 W 32nd St #1410",
city: "New York",
state: "NY",
zip: "10001",
datePlayed: new Date("11/4/17"),
fini: true,
won: true,
playedWith: "Omer, James Carson, Jason Richard, Marketa, Sam"
},{
gameName: "The Experiment",
company: "Escape Games NYC",
address: "79 Leonard St",
city: "New York",
state: "NY",
zip: "10013",
datePlayed: new Date("11/4/17"),
fini: true,
won: true,
playedWith: "Omer, James Carson, Jason Richard, Marketa, Ben Rosner"
},{
gameName: "Manhattan Mayhem",
company: "Escape Entertainment",
address: "39 West 32nd Street, 4th Floor",
city: "New York",
state: "NY",
zip: "10001",
datePlayed: new Date("11/5/17"),
fini: true,
won: true,
playedWith: "Ace Ellett, Anna White, Blayne Adams, Jennifer"
},{
gameName: "TH3 COD3",
company: "Escapology",
address: "2797 S Maryland Pkwy",
city: "Las Vegas",
state: "NV",
zip: "89109",
datePlayed: new Date("11/10/17"),
fini: true,
won: true,
playedWith: "Sharron, Bailey"
},{
gameName: "Casino Takeover",
company: "ESCAPEability",
address: "3100 S. Durango #106",
city: "Las Vegas",
state: "NV",
zip: "89117",
datePlayed: new Date("2/3/18"),
fini: true,
won: true,
playedWith: "Sharron"
},{
gameName: "Jungala",
company: "Escape Reality",
address: "5182 Arville St.",
city: "Las Vegas",
state: "NV",
zip: "89118",
datePlayed: new Date("2/9/18"),
fini: true,
won: true,
playedWith: "Sharron, Bailey, Matt"
},{
gameName: "Mansion Murder",
company: "Escapology",
address: "2797 S Maryland Pkwy",
city: "Las Vegas",
state: "NV",
zip: "89109",
datePlayed: new Date("2/17/18"),
fini: false,
won: false,
playedWith: "Seth"
},{
gameName: "aXe Raiders",
company: "Ameri Escape",
address: "210 E Charleston Blvd",
city: "Las Vegas",
state: "NV",
zip: "89104",
datePlayed: new Date("2/17/18"),
fini: true,
won: true,
playedWith: "Seth"
},{
gameName: "Down the Rabbit Hole",
company: "Escape Reality",
address: "5182 Arville St.",
city: "Las Vegas",
state: "NV",
zip: "89118",
datePlayed: new Date("2/17/18"),
fini: false,
won: false,
playedWith: "Seth"
},{
gameName: "The Cabin",
company: "Number One Escape Room",
address: "1775 East Tropicana",
city: "Las Vegas",
state: "NV",
zip: "89119",
datePlayed: new Date("2/17/18"),
fini: true,
won: true,
playedWith: "Seth"
},{
gameName: "The Heist",
company: "Rush to Escape",
address: "2185 E. Windmill Lane",
city: "Las Vegas",
state: "NV",
zip: "89021",
datePlayed: new Date("2/17/18"),
fini: true,
won: true,
playedWith: "Seth"
},{
gameName: "Iron Kingdom",
company: "Escape Reality",
address: "5182 Arville St.",
city: "Las Vegas",
state: "NV",
zip: "89118",
datePlayed: new Date("4/7/18"),
fini: true,
won: true,
playedWith: "Sharron"
},{
gameName: "Narco",
company: "Escapology",
address: "2797 S Maryland Pkwy",
city: "Las Vegas",
state: "NV",
zip: "89109",
datePlayed: new Date("4/8/18"),
fini: true,
won: true,
playedWith: "Sharron, Avery"
},{
gameName: "Mayan",
company: "Lockdown Flamingo",
address: "4437 W. Flamingo Road",
city: "Las Vegas",
state: "NV",
zip: "89103",
datePlayed: new Date("6/2/18"),
fini: false,
won: false,
playedWith: "Sharron, Bailey, Avery"
},{
gameName: "Revolution/Clock Tower",
company: "Escape Key",
address: "9480 S Eastern Ave, Suite 220",
city: "Henderson",
state: "NV",
zip: "89123",
datePlayed: new Date("6/30/18"),
fini: true,
won: false,
playedWith: "Sharron"
},{
gameName: "The Legacy Room",
company: "HeadzUP/BrainyActz",
address: "Boulevard Mall, 3542 Maryland Parkway",
city: "Las Vegas",
state: "NV",
zip: "89169",
datePlayed: new Date("7/4/18"),
fini: true,
won: false,
playedWith: "Sharron"
},{
gameName: "The Temple",
company: "Unity Escape",
address: "2015 W Park Ave, Suite 2B",
city: "Redlands",
state: "CA",
zip: "92373",
datePlayed: new Date("7/18/18"),
fini: true,
won: true,
playedWith: "Sharron"
},{
gameName: "Toymaker's Workshop",
company: "Escape Games Riverside",
address: "6700 Indiana�Ave. #235",
city: "Riverside",
state: "CA",
zip: "92506",
datePlayed: new Date("7/18/18"),
fini: false,
won: false,
playedWith: "Sharron"
},{
gameName: "Gold Rush",
company: "MindTrap Escape Room",
address: "26780 Ynez Court, Suite C",
city: "Temecula",
state: "CA",
zip: "92591",
datePlayed: new Date("7/19/18"),
fini: true,
won: true,
playedWith: "Sharron"
},{
gameName: "Conspiracy",
company: "MindTrap Escape Room",
address: "26780 Ynez Court, Suite C",
city: "Temecula",
state: "CA",
zip: "92591",
datePlayed: new Date("7/19/18"),
fini: true,
won: false,
playedWith: "Sharron"
},{
gameName: "Uncle Thaddius's Attic",
company: "Get a Clue Escape Room",
address: "27420 Jefferson Ave, Suite 104A",
city: "Temecula",
state: "CA",
zip: "92590",
datePlayed: new Date("7/20/19"),
fini: false,
won: false,
playedWith: "Sharron"
},{
gameName: "Magic Kingdom",
company: "Maze Room Escape Games",
address: "132 S Vermont Ave Unit 204",
city: "Los Angeles",
state: "CA",
zip: "90004",
datePlayed: new Date("7/20/19"),
fini: true,
won: true,
playedWith: "Sharron"
},{
gameName: "Titanic",
company: "60 Out",
address: "13336 Beach Avenue",
city: "Marina Del Rey",
state: "CA",
zip: "90292",
datePlayed: new Date("7/21/18"),
fini: false,
won: false,
playedWith: "Sharron"
},{
gameName: "Wizard's Workshop",
company: "60 Out",
address: "13336 Beach Avenue",
city: "Marina Del Rey",
state: "CA",
zip: "90292",
datePlayed: new Date("7/21/18"),
fini: true,
won: false,
playedWith: "Sharron"
},{
gameName: "Secrets of the Master",
company: "HeadzUP/BrainyActz",
address: "Boulevard Mall, 3542 Maryland Parkway",
city: "Las Vegas",
state: "NV",
zip: "89169",
datePlayed: new Date("8/12/18"),
fini: true,
won: false,
playedWith: "Sharron"
}]
